# Generated by Django 2.1.7 on 2019-03-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joke', '0002_article_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
