# Generated by Django 2.1.7 on 2019-03-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joke', '0003_auto_20190313_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(default='上海', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='description',
            field=models.TextField(default='哈哈哈哈哈哈哈哈'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default='123456789', max_length=32),
            preserve_default=False,
        ),
    ]
